b1, b2 = map(int, input().split())
d1, d2 = map(int, input().split())
j1, j2 = map(int, input().split())
a = max(abs(j1 - b1), abs(j2 - b2))
b = abs(j1 - d1) + abs(j2 - d2)
if a > b: print("daisy")
elif a == b: print("tie")
else: print("bessie")