SELECT 
I.FOOD_TYPE, 
(SELECT REST_ID FROM REST_INFO WHERE FAVORITES = MAX(I.FAVORITES) AND FOOD_TYPE = I.FOOD_TYPE) 
AS REST_ID, 
(SELECT REST_NAME FROM REST_INFO WHERE FAVORITES = MAX(I.FAVORITES) AND FOOD_TYPE = I.FOOD_TYPE) 
AS REST_NAME, 
MAX(I.FAVORITES) AS FAVORITES
FROM REST_INFO I
GROUP BY FOOD_TYPE 
ORDER BY FOOD_TYPE DESC