SELECT ICECREAM_INFO.FLAVOR 
FROM ICECREAM_INFO
INNER JOIN FIRST_HALF 
ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE (FIRST_HALF.TOTAL_ORDER > 3000
AND ICECREAM_INFO.INGREDIENT_TYPE = "fruit_based")
ORDER BY FIRST_HALF.TOTAL_ORDER DESC;